{% set name = "scientific-pydantic" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/scientific_pydantic-{{ version }}.tar.gz
  sha256: 693969685e349856f4ca37353e3d940af9741f7e2f9fba48179cb51fd8352917

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - uv-build >=0.8.3,<0.9.0
    - pip
  run:
    - python >={{ python_min }}
    - pydantic >=2.0

test:
  imports:
    - scientific_pydantic
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://pypi.org/project/scientific-pydantic/
  summary: Pydantic adapters for common scientific types
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - psalvaggio
